### ISSUE TITLE
Spec export: in 3.7 export of symbols not working

### ISSUE THREAD

**Issue by bustablasta** [utom/sketch-measure#102]
If a symbol is made exportable no slice will be produced in spec export and the item is not even clickable.

**Comment by sashagolds** [comment]
Just to elaborate on this:

Sketch Measure will not measure, export specs on, or otherwise interact with any object OR artboard that has been turned into a Symbol (to be clear, I am referring to the original, editable instance of a given symbol or artboard-symbol, not child instances).

This is probably related to the change in the way Symbols work in 3.7. It is particularly problematic because the 3.7 update makes symbols far more pervasive and useful, and many designers (myself included) are using them as a regular part of their workflow now.

*To replicate:*
Create two objects on an artboard, turn the artboard into a symbol then try to measure the distance between the 2 objects (or perform any other Sketch Measure function) on those objects. Sketch will generate the error: "You Need an Artboard” / “You need to select 1 or multiple artboards”.

**Comment by utom** [comment]
try to last version
