### ISSUE TITLE
[Feature Request] Integrate with Sketchpacks Relay to serve auto-updates

### ISSUE THREAD

**Issue by adamkirkwood** [utom/sketch-measure#282]
More details found @ https://github.com/integration/sketchpacks-relay

Example
![screen shot 2017-03-22 at 4 08 57 pm](https://cloud.githubusercontent.com/assets/52746/24224720/fc40de64-0f19-11e7-8473-a2798193fc33.png)

**Comment by luxlogica** [comment]
Better support for [Sketchpacks](https://sketchpacks.com/) would be appreciated. 

Integrating your GitHub project with Sketchpack is not difficult at all, and quite automated - just head over to their [autorelay integration page](https://github.com/integration/sketchpacks-relay), and click the 'instal' button to get started. 

Make sure that the `manifest.json` is present in your repo, and add the Sketchpacks button to your installation instructions, so users know that you support it! 👍

**Comment by luxlogica** [comment]
**DO NOT USE SKETCHPACKS TO LOAD SKETCH-MEASURE**

Unfortunately, Sketchpacks at the moment will load version 2.4.1 of Sketch-Measure, as described in #279 - which presents with breaking bugs in the latest version of Sketch. Until Sketch-Measure provides support for Sketchpacks, the only way to guarantee you're using the latest, bug-free version is to **install it manually**.

**Comment by willdavis** [comment]
@luxlogica it looks like we had an issue on Sketchpack's side where releases were not being correctly updated in the registry.  I've fixed this on the API and you should now be getting any new versions for `sketch-measure`.

Please note though that the update task runs daily, so new releases might not be immediately available.

**Comment by luxlogica** [comment]
@willdavis Thank you for looking into this, and clarifying. Unfortunately, Sketchpacks still seems to be loading the old version of Sketch-Measure for me. Sketchpacks tells me I have the latest version - v0.5.4. When I click on the 'Popular' tab, the first plugin that shows on the list is Sketch Measure, and it shows like this:

<img width="577" alt="screen shot 2017-04-05 at 7 42 10 am" src="https://cloud.githubusercontent.com/assets/2994472/24680328/d83391be-19d3-11e7-9890-0cd6808886a1.png">

Note the "0.0.0" on the version number... If I go ahead and instal it, then ask Sketchpacks to 'Check for Plugin Updates', it *does* update Sketch Measure, but what I end up with is this:

<img width="575" alt="screen shot 2017-04-05 at 7 41 37 am" src="https://cloud.githubusercontent.com/assets/2994472/24680392/1ddec094-19d4-11e7-9242-832cc8814ddd.png">

Note how the version installed is still "2.4.1". It has been about 24 hours since you posted the comment above, so I'm guessing that either your manual update didn't 'stick', or your automatic update task might have screwed up your correction, and reverted to the old version...

**Comment by willdavis** [comment]
Hi @luxlogica, thanks for the detailed feedback!
I was able to track down the bug and the fix is live on production:

![image](https://cloud.githubusercontent.com/assets/1072649/24686315/edade470-1967-11e7-896a-964f53c7e082.png)

Unfortunately, I can't fix the `0.0.0` on the Popular page at this time.  This is due to JSON parse errors in the `manifest.json` for sketch-measure.  The JSON library for Sketchpacks API is on the stricter side and cannot accept trailing commas.

**However, the auto-updates will be able to see the newest versions**

This is the offending line in the `manifest.json`: https://github.com/utom/sketch-measure/blob/master/Sketch%20Measure.sketchplugin/Contents/Sketch/manifest.json#L130

**Comment by luxlogica** [comment]
@willdavis Thank you so much for your prompt response, and your detailed feedback. I hope this will make it easy for the Sketch Measure guys to fix their problem with their `manifest.json` - and hopefully, add *auto-update support*, too! ;-)

Once again, many thanks!

**Comment by utom** [comment]
**auto-update support**
