### ISSUE TITLE
Broken on Sketch 3.4

### ISSUE THREAD

**Issue by foxintherain** [utom/sketch-measure#71]
When trying to use the plugin in Sketch 3.4, a pop-up appears with the following:

"Make sure you've selected a symbol, or a layer that."

**Comment by utom** [comment]
Are you sure your plugin is last version?

**Comment by foxintherain** [comment]
Seems to be working now, must have updated :)

**Comment by moeffju** [comment]
I’m using the plugin with Sketch 3.4 and it’s simply not doing anything. Tried reinstalling from master to no avail. Any ideas?

**Comment by lostsatellites** [comment]
I noticed that the plugin would work if I only had one document open, but with more than one open in 3.4 it will not.

**Comment by pandasaurusrex** [comment]
Definitely not working properly in Sketch 3.4.2 ... If there's more than one Sketch file open, I either get the above pop-up ("Make sure you've selected a symbol, or a layer that.") OR it tries to perform the measuring on random layers in one of the open files (instead of the currently selected layer in the foremost open file). As @lostsatellites mentioned, the plugin works fine if there's just 1 doc open.

**Comment by nitrada** [comment]
True for every plugin. Fixed in 3.4.3 :)

**Comment by utom** [comment]
Update Sketch to 3.4.3, it had fix~

**Comment by utom** [comment]
@nitrada thank you

**Comment by ifthenjim** [comment]
Apparently not working properly in Sketch 3.4.4 update.
